-- 2026-07-21: El ERP agregó la columna SAC al DBF de SUELDOS_LIQUIDACIONES.
-- El ETL fallaba con "Invalid column name 'SAC'" al intentar cargar registros de 2026.
-- SAC es un flag booleano que indica si la liquidación incluye SAC (Sueldo Anual Complementario).

ALTER TABLE EMPR0001.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0002.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0003.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0004.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0005.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0006.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0007.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0008.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0009.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0010.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0011.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0012.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0013.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR0014.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
ALTER TABLE EMPR7000.SUELDOS_LIQUIDACIONES ADD SAC bit NULL;
