-- vw_Compras_FacturasPendientes
-- Facturas, ND y NC de proveedores genuinamente pendientes de pago.
-- Saldo real = TOTAL - suma de imputaciones/pagos con FONDO<>'0' (excluye ajustes contra otras compras).
-- Se incluye si CTACTE > 0 (crédito normal) O si tiene algún pago registrado en RELACIONESCTASCTES
-- (caso CONALLISON: CTACTE=0 pero el operador crea OPs y las imputa a las facturas).
-- Esto excluye compras contado genuinas (CTACTE=0 y sin imputaciones) que son falsos positivos.
-- EMPR0023 no tiene RELACIONESCTASCTES; se cae al criterio CTACTE<>0.

CREATE OR ALTER VIEW dbo.vw_Compras_FacturasPendientes AS

WITH Empresas AS (
    SELECT Empresa, NombreEmpresa FROM dbo.Config_Empresas
)

SELECT
    'EMPR0001'  AS EmpresaId,
    ce.NombreEmpresa,
    lc.CODIGO   AS CodigoFactura,
    lc.PROVEEDOR AS CodigoProveedor,
    e.NOMBRE    AS NombreProveedor,
    e.CUIT,
    lc.COMPROB  AS CodigoComprobante,
    cc.NOMBRE   AS TipoComprobante,
    lc.PTOEMISOR,
    lc.NUMERO,
    RIGHT('0000' + CAST(lc.PTOEMISOR AS nvarchar(10)), 4) + '-'
        + RIGHT('00000000' + CAST(lc.NUMERO AS nvarchar(20)), 8) AS NroComprobante,
    lc.FECHA    AS FechaFactura,
    lc.VENCE    AS FechaVencimiento,
    lc.TOTAL,
    lc.CTACTE                                          AS ImporteCtaCte,
    ISNULL(p.TotalPagado, 0)                           AS TotalPagado,
    lc.TOTAL - ISNULL(p.TotalPagado, 0)                AS SaldoPendiente,
    lc.MONEDA,
    lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)) AS DiasAtraso,
    lc.PERIODO,
    lc.COMENTARIO
FROM EMPR0001.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0001'
LEFT JOIN EMPR0001.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0001.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (
    SELECT COMPRA, SUM(IMPORTE) AS TotalPagado
    FROM EMPR0001.OFICIAL_RELACIONESCTASCTES
    WHERE FONDO <> '0'
    GROUP BY COMPRA
) p ON p.COMPRA = lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado, 0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado, 0) > 0)

UNION ALL

SELECT 'Empr0002', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM Empr0002.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'Empr0002'
LEFT JOIN Empr0002.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN Empr0002.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM Empr0002.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0003', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0003.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0003'
LEFT JOIN EMPR0003.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0003.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0003.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0004', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0004.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0004'
LEFT JOIN EMPR0004.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0004.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0004.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0005', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0005.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0005'
LEFT JOIN EMPR0005.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0005.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0005.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0006', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0006.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0006'
LEFT JOIN EMPR0006.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0006.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0006.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0007', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0007.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0007'
LEFT JOIN EMPR0007.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0007.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0007.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0009', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0009.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0009'
LEFT JOIN EMPR0009.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0009.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0009.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0010', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0010.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0010'
LEFT JOIN EMPR0010.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0010.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0010.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0011', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0011.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0011'
LEFT JOIN EMPR0011.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0011.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0011.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0012', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0012.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0012'
LEFT JOIN EMPR0012.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0012.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0012.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0013', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0013.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0013'
LEFT JOIN EMPR0013.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0013.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0013.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0014', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0014.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0014'
LEFT JOIN EMPR0014.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0014.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0014.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0015', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0015.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0015'
LEFT JOIN EMPR0015.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0015.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0015.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0016', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0016.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0016'
LEFT JOIN EMPR0016.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0016.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0016.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0017', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0017.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0017'
LEFT JOIN EMPR0017.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0017.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0017.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0018', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0018.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0018'
LEFT JOIN EMPR0018.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0018.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0018.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0020', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0020.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0020'
LEFT JOIN EMPR0020.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0020.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0020.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0021', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0021.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0021'
LEFT JOIN EMPR0021.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0021.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0021.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

SELECT 'EMPR0022', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0022.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0022'
LEFT JOIN EMPR0022.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0022.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0022.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0)

UNION ALL

-- EMPR0023: sin RELACIONESCTASCTES, se usa solo CTACTE
SELECT 'EMPR0023', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, CAST(0 AS numeric(18,2)), lc.CTACTE,
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0023.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0023'
LEFT JOIN EMPR0023.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0023.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
WHERE lc.CTACTE <> 0

UNION ALL

SELECT 'EMPR0024', ce.NombreEmpresa,
    lc.CODIGO, lc.PROVEEDOR, e.NOMBRE, e.CUIT,
    lc.COMPROB, cc.NOMBRE, lc.PTOEMISOR, lc.NUMERO,
    RIGHT('0000'+CAST(lc.PTOEMISOR AS nvarchar(10)),4)+'-'+RIGHT('00000000'+CAST(lc.NUMERO AS nvarchar(20)),8),
    lc.FECHA, lc.VENCE, lc.TOTAL,
    lc.CTACTE, ISNULL(p.TotalPagado,0), lc.TOTAL - ISNULL(p.TotalPagado,0),
    lc.MONEDA, lc.TIPOCAMBIO,
    DATEDIFF(day, lc.VENCE, CAST(GETDATE() AS date)), lc.PERIODO, lc.COMENTARIO
FROM EMPR0024.OFICIAL_LIBROCOMPRAS lc
JOIN Empresas ce ON ce.Empresa = 'EMPR0024'
LEFT JOIN EMPR0024.OFICIAL_ENTIDADES e ON e.CODIGO = lc.PROVEEDOR
LEFT JOIN EMPR0024.OFICIAL_CLASECOMPROBANTES cc ON cc.CODIGO = lc.COMPROB
LEFT JOIN (SELECT COMPRA, SUM(IMPORTE) AS TotalPagado FROM EMPR0024.OFICIAL_RELACIONESCTASCTES WHERE FONDO<>'0' GROUP BY COMPRA) p ON p.COMPRA=lc.CODIGO
WHERE lc.TOTAL - ISNULL(p.TotalPagado,0) > 0.01
      AND (lc.CTACTE > 0 OR ISNULL(p.TotalPagado,0) > 0);
