-- =============================================================================
-- vw_Sueldos_Nomina
-- Nomina consolidada de empleados de las 15 empresas del ERP Senales.
-- Una fila por contrato (un empleado con varios contratos = varias filas).
-- Empleados sin contrato aparecen con EstadoLaboral='SinContrato'.
--
-- Enriquecimientos:
--   - RazonSocial          via dbo.Config_Empresas_Sueldos
--   - UltimoPuesto         ultimo registro en SUELDOS_EMPLEADOSXPUESTOS por empleado
--   - UltimoCentroCosto    ultimo registro en SUELDOS_EMPLEADOSXCENTROCOSTO por empleado
--   - SindicatoNombre      via dbo.Config_Sindicatos (hoy esta vacia, queda preparado)
-- =============================================================================
CREATE OR ALTER VIEW dbo.vw_Sueldos_Nomina
AS
WITH Empleados AS (
    SELECT 'EMPR0001' AS Empresa, CODIGO AS IdEmpleado, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0001.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'Empr0002', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM Empr0002.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0003', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0003.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0004', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0004.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0005', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0005.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0006', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0006.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0007', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0007.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0008', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0008.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0009', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0009.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0010', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0010.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0011', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0011.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0012', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0012.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0013', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0013.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR0014', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR0014.SUELDOS_EMPLEADOS
    UNION ALL SELECT 'EMPR7000', CODIGO, NOMBRE, CUIL, FCHNACIM, FCHANTIG, FCHJUBILAC, SEXO, ESTCIVIL, SINDICATO, OBRASOCIAL, CONDICION, MODALIDAD, BASICO FROM EMPR7000.SUELDOS_EMPLEADOS
),
Contratos AS (
    SELECT 'EMPR0001' AS Empresa, EMPLEADO AS IdEmpleado, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0001.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'Empr0002', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM Empr0002.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0003', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0003.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0004', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0004.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0005', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0005.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0006', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0006.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0007', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0007.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0008', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0008.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0009', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0009.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0010', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0010.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0011', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0011.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0012', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0012.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0013', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0013.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR0014', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR0014.SUELDOS_CONTRATOSXEMPLEADO
    UNION ALL SELECT 'EMPR7000', EMPLEADO, CONTRATO, INGRESO, EGRESO, CAUSABAJA, PROPORCION, PROPORCSAC FROM EMPR7000.SUELDOS_CONTRATOSXEMPLEADO
),
PuestosHistoria AS (
    SELECT 'EMPR0001' AS Empresa, EMPLEADO AS IdEmpleado, ESTABLECIM, PUESTO, FECHA FROM EMPR0001.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'Empr0002', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM Empr0002.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0003', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0003.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0004', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0004.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0005', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0005.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0006', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0006.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0007', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0007.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0008', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0008.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0009', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0009.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0010', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0010.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0011', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0011.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0012', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0012.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0013', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0013.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR0014', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR0014.SUELDOS_EMPLEADOSXPUESTOS
    UNION ALL SELECT 'EMPR7000', EMPLEADO, ESTABLECIM, PUESTO, FECHA FROM EMPR7000.SUELDOS_EMPLEADOSXPUESTOS
),
UltimoPuesto AS (
    SELECT Empresa, IdEmpleado, ESTABLECIM, PUESTO, FECHA,
           ROW_NUMBER() OVER (PARTITION BY Empresa, IdEmpleado ORDER BY FECHA DESC, PUESTO DESC) AS rn
    FROM PuestosHistoria
),
PuestosMaestro AS (
    SELECT 'EMPR0001' AS Empresa, CODIGO AS PuestoCod, NOMBRE AS PuestoNombre, SINDICATO AS PuestoSindicato FROM EMPR0001.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'Empr0002', CODIGO, NOMBRE, SINDICATO FROM Empr0002.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0003', CODIGO, NOMBRE, SINDICATO FROM EMPR0003.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0004', CODIGO, NOMBRE, SINDICATO FROM EMPR0004.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0005', CODIGO, NOMBRE, SINDICATO FROM EMPR0005.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0006', CODIGO, NOMBRE, SINDICATO FROM EMPR0006.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0007', CODIGO, NOMBRE, SINDICATO FROM EMPR0007.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0008', CODIGO, NOMBRE, SINDICATO FROM EMPR0008.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0009', CODIGO, NOMBRE, SINDICATO FROM EMPR0009.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0010', CODIGO, NOMBRE, SINDICATO FROM EMPR0010.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0011', CODIGO, NOMBRE, SINDICATO FROM EMPR0011.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0012', CODIGO, NOMBRE, SINDICATO FROM EMPR0012.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0013', CODIGO, NOMBRE, SINDICATO FROM EMPR0013.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR0014', CODIGO, NOMBRE, SINDICATO FROM EMPR0014.SUELDOS_PUESTOSTRABAJO
    UNION ALL SELECT 'EMPR7000', CODIGO, NOMBRE, SINDICATO FROM EMPR7000.SUELDOS_PUESTOSTRABAJO
),
CentrosHistoria AS (
    SELECT 'EMPR0001' AS Empresa, EMPLEADO AS IdEmpleado, CTROCOSTO, FECHA FROM EMPR0001.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'Empr0002', EMPLEADO, CTROCOSTO, FECHA FROM Empr0002.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0003', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0003.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0004', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0004.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0005', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0005.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0006', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0006.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0007', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0007.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0008', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0008.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0009', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0009.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0010', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0010.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0011', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0011.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0012', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0012.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0013', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0013.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR0014', EMPLEADO, CTROCOSTO, FECHA FROM EMPR0014.SUELDOS_EMPLEADOSXCENTROCOSTO
    UNION ALL SELECT 'EMPR7000', EMPLEADO, CTROCOSTO, FECHA FROM EMPR7000.SUELDOS_EMPLEADOSXCENTROCOSTO
),
UltimoCentro AS (
    SELECT Empresa, IdEmpleado, CTROCOSTO, FECHA,
           ROW_NUMBER() OVER (PARTITION BY Empresa, IdEmpleado ORDER BY FECHA DESC, CTROCOSTO DESC) AS rn
    FROM CentrosHistoria
),
CentrosMaestro AS (
    SELECT 'EMPR0001' AS Empresa, CODIGO AS CtroCostoCod, NOMBRE AS CtroCostoNombre FROM EMPR0001.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'Empr0002', CODIGO, NOMBRE FROM Empr0002.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0003', CODIGO, NOMBRE FROM EMPR0003.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0004', CODIGO, NOMBRE FROM EMPR0004.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0005', CODIGO, NOMBRE FROM EMPR0005.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0006', CODIGO, NOMBRE FROM EMPR0006.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0007', CODIGO, NOMBRE FROM EMPR0007.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0008', CODIGO, NOMBRE FROM EMPR0008.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0009', CODIGO, NOMBRE FROM EMPR0009.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0010', CODIGO, NOMBRE FROM EMPR0010.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0011', CODIGO, NOMBRE FROM EMPR0011.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0012', CODIGO, NOMBRE FROM EMPR0012.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0013', CODIGO, NOMBRE FROM EMPR0013.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR0014', CODIGO, NOMBRE FROM EMPR0014.SUELDOS_CENTROSCOSTOS
    UNION ALL SELECT 'EMPR7000', CODIGO, NOMBRE FROM EMPR7000.SUELDOS_CENTROSCOSTOS
)
SELECT
    e.Empresa,
    ce.NombreEmpresa                                AS RazonSocial,
    e.IdEmpleado,
    c.CONTRATO                                      AS ContratoNro,
    e.CUIL,
    e.NOMBRE                                        AS NombreEmpleado,
    e.FCHNACIM                                      AS FchNacimiento,
    e.FCHANTIG                                      AS FchAntiguedad,
    e.FCHJUBILAC                                    AS FchJubilacion,
    e.SEXO                                          AS SexoCod,
    e.ESTCIVIL                                      AS EstadoCivilCod,
    e.SINDICATO                                     AS SindicatoCod,
    cs.NombreSindicato                              AS SindicatoNombre,
    e.OBRASOCIAL                                    AS ObraSocialCod,
    e.CONDICION                                     AS CondicionCod,
    e.MODALIDAD                                     AS ModalidadCod,
    e.BASICO                                        AS BasicoMaestro,
    c.INGRESO                                       AS FechaIngreso,
    c.EGRESO                                        AS FechaEgreso,
    NULLIF(LTRIM(RTRIM(c.CAUSABAJA)), '')           AS CausaBajaOficial,
    c.PROPORCION                                    AS Proporcion,
    c.PROPORCSAC                                    AS ProporcionSac,
    up.PUESTO                                       AS UltimoPuestoCod,
    pm.PuestoNombre                                 AS UltimoPuestoNombre,
    up.ESTABLECIM                                   AS UltimoEstablecimientoCod,
    up.FECHA                                        AS UltimoPuestoFecha,
    uc.CTROCOSTO                                    AS UltimoCtroCostoCod,
    cm.CtroCostoNombre                              AS UltimoCtroCostoNombre,
    uc.FECHA                                        AS UltimoCtroCostoFecha,
    CASE
        WHEN c.CONTRATO IS NULL                                THEN 'SinContrato'
        WHEN c.EGRESO IS NULL                                  THEN 'Activo'
        WHEN c.EGRESO > CAST(GETDATE() AS date)                THEN 'Activo'
        ELSE                                                       'Baja'
    END                                             AS EstadoLaboral,
    CASE WHEN c.EGRESO IS NOT NULL AND c.EGRESO <= CAST(GETDATE() AS date)
         THEN DATEDIFF(day, c.INGRESO, c.EGRESO)
         WHEN c.INGRESO IS NOT NULL
         THEN DATEDIFF(day, c.INGRESO, CAST(GETDATE() AS date))
         ELSE NULL
    END                                             AS DiasContrato
FROM Empleados e
LEFT JOIN Contratos c
       ON c.Empresa = e.Empresa AND c.IdEmpleado = e.IdEmpleado
LEFT JOIN dbo.Config_Empresas_Sueldos ce
       ON ce.Empresa = e.Empresa
LEFT JOIN dbo.Config_Sindicatos cs
       ON cs.Empresa = e.Empresa AND cs.CodigoSindicato = e.SINDICATO
LEFT JOIN UltimoPuesto up
       ON up.Empresa = e.Empresa AND up.IdEmpleado = e.IdEmpleado AND up.rn = 1
LEFT JOIN PuestosMaestro pm
       ON pm.Empresa = e.Empresa AND pm.PuestoCod = up.PUESTO
LEFT JOIN UltimoCentro uc
       ON uc.Empresa = e.Empresa AND uc.IdEmpleado = e.IdEmpleado AND uc.rn = 1
LEFT JOIN CentrosMaestro cm
       ON cm.Empresa = e.Empresa AND cm.CtroCostoCod = uc.CTROCOSTO;
