-- ============================================================================
-- VISTA: dbo.vw_Sueldos_Establecimientos
-- ----------------------------------------------------------------------------
-- Consolida los SUELDOS_ESTABLECIMIENTOS por empresa. Cada fila es una sucursal.
-- ============================================================================
CREATE OR ALTER VIEW dbo.vw_Sueldos_Establecimientos
AS
SELECT 'EMPR0001' AS Empresa, CODIGO AS IdEstablecimiento, NOMBRE AS Establecimiento, ACTIVIDAD, LOCALIDAD FROM EMPR0001.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'Empr0002', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM Empr0002.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0003', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0003.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0004', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0004.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0005', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0005.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0006', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0006.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0007', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0007.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0008', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0008.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0009', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0009.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0010', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0010.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0011', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0011.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0012', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0012.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0013', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0013.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR0014', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR0014.SUELDOS_ESTABLECIMIENTOS
UNION ALL SELECT 'EMPR7000', CODIGO, NOMBRE, ACTIVIDAD, LOCALIDAD FROM EMPR7000.SUELDOS_ESTABLECIMIENTOS;
