-- ============================================================================
-- VISTA: dbo.vw_Sueldos_ContribucionesXEmpleado
-- ----------------------------------------------------------------------------
-- Contribuciones patronales por empleado/liquidacion/periodo. Es la fuente del
-- componente patronal del costo empresa (jubilacion patronal, obra social
-- patronal, ART, sindicales patronales, etc.) -- NO confundir con categoria
-- APORTE en vw_Sueldos_ReciboDetalle_Normalizado que son descuentos al empleado.
-- ============================================================================
CREATE OR ALTER VIEW dbo.vw_Sueldos_ContribucionesXEmpleado
AS
SELECT 'EMPR0001' AS Empresa, EMPLEADO AS IdEmpleado, CONTRIBUC AS IdContribucion, LIQUIDAC AS IdLiquidacion, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM EMPR0001.SUELDOS_CONTRIBUCIONESXEMPLEADO
UNION ALL SELECT 'Empr0002', EMPLEADO, CONTRIBUC, LIQUIDAC, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM Empr0002.SUELDOS_CONTRIBUCIONESXEMPLEADO
UNION ALL SELECT 'EMPR0003', EMPLEADO, CONTRIBUC, LIQUIDAC, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM EMPR0003.SUELDOS_CONTRIBUCIONESXEMPLEADO
UNION ALL SELECT 'EMPR0005', EMPLEADO, CONTRIBUC, LIQUIDAC, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM EMPR0005.SUELDOS_CONTRIBUCIONESXEMPLEADO
UNION ALL SELECT 'EMPR0006', EMPLEADO, CONTRIBUC, LIQUIDAC, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM EMPR0006.SUELDOS_CONTRIBUCIONESXEMPLEADO
UNION ALL SELECT 'EMPR0007', EMPLEADO, CONTRIBUC, LIQUIDAC, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM EMPR0007.SUELDOS_CONTRIBUCIONESXEMPLEADO
UNION ALL SELECT 'EMPR0009', EMPLEADO, CONTRIBUC, LIQUIDAC, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM EMPR0009.SUELDOS_CONTRIBUCIONESXEMPLEADO
UNION ALL SELECT 'EMPR0010', EMPLEADO, CONTRIBUC, LIQUIDAC, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM EMPR0010.SUELDOS_CONTRIBUCIONESXEMPLEADO
UNION ALL SELECT 'EMPR0011', EMPLEADO, CONTRIBUC, LIQUIDAC, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM EMPR0011.SUELDOS_CONTRIBUCIONESXEMPLEADO
UNION ALL SELECT 'EMPR0012', EMPLEADO, CONTRIBUC, LIQUIDAC, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM EMPR0012.SUELDOS_CONTRIBUCIONESXEMPLEADO
UNION ALL SELECT 'EMPR0013', EMPLEADO, CONTRIBUC, LIQUIDAC, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM EMPR0013.SUELDOS_CONTRIBUCIONESXEMPLEADO
UNION ALL SELECT 'EMPR0014', EMPLEADO, CONTRIBUC, LIQUIDAC, PERIODO, MONTOBASE, ALICUOTA, MONTOFIJO, MONTOCONTR FROM EMPR0014.SUELDOS_CONTRIBUCIONESXEMPLEADO;
-- EMPR0004, EMPR0008, EMPR7000 no tienen tabla SUELDOS_CONTRIBUCIONESXEMPLEADO.
